FROM alpine:3.20.2
LABEL authors="your name"

# you might install alpine software packages, fx curl
# RUN apk update && apk add curl

# note: thare are also native images for curl, hugo, jekyll, llm, ...

ENTRYPOINT ["top"]
CMD ["-b"]